[tool.black]
line-length = 79
target-version = ["py39"]


[tool.isort]
profile = "black"
line_length = 79
multi_line_output = 3
lines_after_imports = 2
case_sensitive = true


[tool.pytest.ini_options]
testpaths = ["tests"]


[tool.mypy]
exclude = "setup.py"

disallow_any_generics = true

disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true

no_implicit_optional = true

warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
warn_unreachable = true

strict_equality = true

show_error_codes = true

warn_unused_configs = true
